
name: kahuna
services:
  kahuna1:
    build:
      context: .. #current dir as build context
      dockerfile: docker/DockerfileLocal
      args:
        KAHUNA_RAFT_NODEID: kahuna1
        KAHUNA_RAFT_HOST: 172.30.0.2
        KAHUNA_RAFT_PORT: 8082
        KAHUNA_HTTP_PORTS: 2070 8081
        KAHUNA_HTTPS_PORTS: 2071 8082
        KAHUNA_INITIAL_CLUSTER: 172.30.0.3:8084 172.30.0.4:8086
    container_name: kahuna1
    ports:
      - "8081:2070"
      - "8082:2071"
    volumes:
      - kahuna1-data:/storage
    networks:
      custom_net:
        ipv4_address: 172.30.0.2

  kahuna2:
    build:
      context: .. #current dir as build context
      dockerfile: docker/DockerfileLocal
      args:
        KAHUNA_RAFT_NODEID: kahuna2
        KAHUNA_RAFT_HOST: 172.30.0.3
        KAHUNA_RAFT_PORT: 8084
        KAHUNA_HTTP_PORTS: 2070 8083
        KAHUNA_HTTPS_PORTS: 2071 8084
        KAHUNA_INITIAL_CLUSTER: 172.30.0.2:8082 172.30.0.4:8086
    container_name: kahuna2
    ports:
      - "8083:2070"
      - "8084:2071"
    volumes:
      - kahuna2-data:/storage
    networks:
      custom_net:
        ipv4_address: 172.30.0.3

  kahuna3:
    build:
      context: .. #current dir as build context
      dockerfile: docker/DockerfileLocal
      args:
        KAHUNA_RAFT_NODEID: kahuna3
        KAHUNA_RAFT_HOST: 172.30.0.4
        KAHUNA_RAFT_PORT: 8086
        KAHUNA_HTTP_PORTS: 2070 8085
        KAHUNA_HTTPS_PORTS: 2071 8086
        KAHUNA_INITIAL_CLUSTER: 172.30.0.2:8082 172.30.0.3:8084
    container_name: kahuna3
    ports:
      - "8085:2070"
      - "8086:2071"
    volumes:
      - kahuna3-data:/storage
    networks:
      custom_net:
        ipv4_address: 172.30.0.4

volumes:
  kahuna1-data:
  kahuna2-data:
  kahuna3-data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
